name: sdl3
description: A Dart library for accessing common SDL3 (and SDL3_image, SDL3_mixer, SDL3_net, SDL3_ttf, SDL3_gfx) APIs using, FFI.
version: 2.4.8
homepage: https://github.com/sansuido/sdl3
repository: https://github.com/sansuido/sdl3

environment:
  sdk: '>=3.10.2 <4.0.0'

dependencies:
  ffi: ^2.1.4

dev_dependencies:
  change_case: ^2.2.0
  halildurmus_lints: ^1.0.1
